version: "3.3"

services:
    
  rabbitmq:    
    image: rabbitmq                 
    container_name: rabbitmq   
    volumes:
     - /opt/rabbitmq/logs/:/opt/rabbitmq/logs
    ports:
     - '15672:15672'
     - '5672:5672'
    networks:
     - socnet
    
  
  
   

networks:
  socnet:
    driver: bridge
