management:
  security:  
   enabled: false      
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'

spring:  
  application:
    name: second
  rabbitmq:
    host: localhost
    port: 5672
  cloud:  
    stream:
      bindings:
        input:
          destination: data-out
        output:
          destination: data-next
          producer:
            partitionKeyExpression: payload.id
            partitionCount: 4
       
      rabbit:
        bindings:          
          input:
            consumer:
              exchangeType: direct

server:  
  port: ${PORT:8091}
